import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Background from '@context/Background'
import { PageWrapper } from '@/components/context/pageContext'
import { useAppContext } from '@/components/context/appContext'
import Title from '@/components/Title'

import ScrollVisual from '@/components/scroll/ScrollVisual'
import ScrollingDiv from '@/components/scroll/ScrollingDiv'
import FadeDiv from '@/components/scroll/FadeDiv'

import SpireeStory from '../public/images/spireeStory.svg'
import Story1Astrid from '@/components/story/Story1Astrid'
import Story2Pharma from '@/components/story/Story2Pharma'
import Story3Mountain from '@/components/story/Story3Mountain'
import Story4Flowers from '@/components/story/Story4Flowers'
import Story5Meaning from '@/components/story/Story5Meaning'
import Story6Spiree from '@/components/story/Story6Spiree'
import Story7SunMoon from '@/components/story/Story7SunMoon'
import Story8Merino from '@/components/story/Story8Merino'
import Story9Passion from '@/components/story/Story9Passion'
import Story10RE from '@/components/story/Story10RE'
import Story11Women from '@/components/story/Story11Women'
import Story12Support from '@/components/story/Story12Support'
import StoryText from '@/components/story/StoryText'


export default function Home({ }) {

  const { scrolled } = useAppContext();

  // useEffect(()=>{
  //   window.scrollTo({
  //     top: 35,
  //     behavior: "smooth",
  // });
  // },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={"w-full h-[3000px]"}>
        <ScrollVisual scrolled={scrolled} />

        <PageWrapper darkMode={true} svgWidth={'w-4/5 xl:w-3/5'} >
          <Background />
          <Title mainTitle={'About Spirée'} subTitle={'Empowering women to run everywhere, with confidence and style.'} />
          
          <section className='flex w-4/5 mx-auto relative' >
            
            <FadeDiv className='fixed w-full h-[80vh] top-[120px] left-1/2 -translate-x-1/2 border-red-700 border' amount={10} type='top'>
            
              <ScrollingDiv className='fixed w-full top-[40px] left-1/2' 
                speed = {0}
                step1 = {{from:0.49, for:350}}
                step2 = {{from: 0.74, for:450}}>

                <Story1Astrid speed={1} scrollMin={0} scrollMax={0} />
                <Story2Pharma speed={1} scrollMin={0} scrollMax={0.125} />
                <Story3Mountain speed={1} scrollMin={0.13} scrollMax={0.2} />
                <Story4Flowers speed={1} scrollMin={0.215} scrollMax={0.35} />
                <Story5Meaning speed={1} scrollMin={0.39} scrollMax={0.42} />
                <Story6Spiree speed={1} scrollMin={0.45} scrollMax={0.53} />
                <Story7SunMoon speed={1} scrollMin={0.55} scrollMax={0.62} />
                <Story8Merino speed={1} scrollMin={0.64} scrollMax={0.71} />
                <Story9Passion speed={1} scrollMin={0.73} scrollMax={0.76} />
                <Story10RE speed={1} scrollMin={0.78} scrollMax={0.82} />
                <Story11Women speed={1} scrollMin={0.83} scrollMax={0.86} />
                <Story12Support speed={1} scrollMin={0.87} scrollMax={0.95} />
                <StoryText/>

              </ScrollingDiv>
            </FadeDiv>
          </section>

          

        </PageWrapper>
      </main>
    </>
  )
}


export async function getStaticProps() {
  //   const pets = await client.fetch(`*[_type == "post"]`);

  return {
    props: {
      //   pets
    }
  };
}

