import Head from 'next/head'
import Image from 'next/image'
import {client, urlFor} from '@lib/sanity'

export default function Home({pets}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"bg-black text-white"}>
        <h1>TEST</h1>
        <h2>pets</h2>
        {pets.length > 0 && (
          <ul>
            {pets.map((pet) => (
              <li key={pet._id}>{pet?.name} <img src={urlFor(pet?.mainImage)}></img></li>
            ))}
          </ul>
        )}
        {!pets.length > 0 && <p>No pets to show</p>}
        {pets.length > 0 && (
          <div>
            <pre>{JSON.stringify(pets, null, 2)}</pre>
          </div>
        )}
        {!pets.length > 0 && (
          <div>
            <div>¯\_(ツ)_/¯</div>
            <p>
              {"Your data will show up here when you've configured everything correctly"}
            </p>
          </div>
        )}
      </main>
    </>
  )
}


export async function getStaticProps() {
  const pets = await client.fetch(`*[_type == "post"]`);

  return {
    props: {
      pets
    }
  };
}

